<template>
  <b-grid-view
    table-striped
    table-hover
    thead-sticky
    table-bordered
    fixedSize="sm"
    fixed="4"
    thead-theme="dark"
    :list="list"
    :head="head"
    selectStatus="select"
    :operate="operate"
    :row-style="rowStyle"
  />
</template>

<script>
import BGridView from "@/components/content/GridView/b-grid-view.vue";

export default {
  name: "BGridViewDemo",
  components: { BGridView },
  data() {
    return {
      head: [
        {
          label: "id",
          field: "id",
          colClass: "bg-info",
          colStyle: "width: 50px;"
        },
        {
          label: "name",
          field: "name",
          colStyle: "width: 100px;",
          format: value => "name_" + value
        },
        { label: "sex", field: "sex", colStyle: "width: 100px;" },
        {
          label: "age",
          field: "age",
          colStyle: "width: 58px;",
          cellStyle: value => {
            return { class: Number(value) ? "bg-success" : "bg-danger" };
          }
        },
        {
          label: "1",
          field: "1",
          children: [
            {
              label: "1-1",
              field: "1-1",
              children: [
                { label: "1-1-1", field: "1-1-1" },
                { label: "1-1-2", field: "1-1-2" }
              ]
            },
            { label: "1-2", field: "1-2" },
            {
              label: "1-3",
              field: "1-3",
              children: [
                { label: "1-3-1", field: "1-3-1" },
                { label: "1-3-2", field: "1-3-2" }
              ]
            }
          ]
        },
        {
          label: "2",
          field: "2",
          children: [
            {
              label: "2-1",
              field: "2-1",
              children: [
                { label: "2-1-1", field: "2-1-1" },
                { label: "2-1-2", field: "2-1-2" }
              ]
            },
            {
              label: "2-2",
              field: "2-2",
              children: [
                { label: "2-2-1", field: "2-2-1" },
                { label: "2-2-2", field: "2-2-2" }
              ]
            },
            { label: "2-3", field: "2-3" }
          ]
        }
      ],
      operate: {
        index: 2,
        value: ["view", "edit", "delete", "flow"]
      },
      rowStyle: {
        class: function(row) {
          if (row && row.age && Number(row.age) == 5) return "text-warning";
        }
      },
      sort: ["sex", "2-1-1", "2-2-2"],
      list: [
        { id: "id_000", name: "mack", sex: "man", age: 10 },
        { id: "id_001", name: "mack", sex: "man", age: 10 },
        { id: "id_002", name: "jack", sex: "man", age: 10 },
        { id: "id_003", name: "mack", sex: "man" },
        { id: "id_004", name: "mack", sex: "man", age: 5 },
        { id: "id_005", name: "mack", sex: "man", age: 5 },
        { id: "id_006", name: "mack", sex: "man", age: 10 },
        { id: "id_007", name: "mack", sex: "man", age: 10 },
        { id: "id_008", name: "mack", sex: "man", age: 10 },
        { id: "id_009", name: "mack", sex: "man", age: 10 },
        { id: "id_010", name: "mack", sex: "man", age: 10 },
        { id: "id_011", name: "mack", sex: "man", age: 10 },
        { id: "id_012", name: "jack", sex: "man", age: 10 },
        { id: "id_013", name: "mack", sex: "man" },
        { id: "id_014", name: "mack", sex: "man", age: 5 },
        { id: "id_015", name: "mack", sex: "man", age: 5 },
        { id: "id_016", name: "mack", sex: "man", age: 10 },
        { id: "id_017", name: "mack", sex: "man", age: 10 },
        { id: "id_018", name: "mack", sex: "man", age: 10 },
        { id: "id_019", name: "mack", sex: "man", age: 10 },
        { id: "id_020", name: "mack", sex: "man", age: 10 },
        { id: "id_021", name: "mack", sex: "man", age: 10 },
        { id: "id_022", name: "jack", sex: "man", age: 10 },
        { id: "id_023", name: "mack", sex: "man" },
        { id: "id_024", name: "mack", sex: "man", age: 5 },
        { id: "id_025", name: "mack", sex: "man", age: 5 },
        { id: "id_026", name: "mack", sex: "man", age: 10 },
        { id: "id_027", name: "mack", sex: "man", age: 10 },
        { id: "id_028", name: "mack", sex: "man", age: 10 },
        { id: "id_029", name: "mack", sex: "man", age: 10 },
        { id: "id_030", name: "mack", sex: "man", age: 10 },
        { id: "id_031", name: "mack", sex: "man", age: 10 },
        { id: "id_032", name: "jack", sex: "man", age: 10 },
        { id: "id_033", name: "mack", sex: "man" },
        { id: "id_034", name: "mack", sex: "man", age: 5 },
        { id: "id_035", name: "mack", sex: "man", age: 5 },
        { id: "id_036", name: "mack", sex: "man", age: 10 },
        { id: "id_037", name: "mack", sex: "man", age: 10 },
        { id: "id_038", name: "mack", sex: "man", age: 10 },
        { id: "id_039", name: "mack", sex: "man", age: 10 },
        { id: "id_040", name: "mack", sex: "man", age: 10 },
        { id: "id_041", name: "mack", sex: "man", age: 10 },
        { id: "id_042", name: "jack", sex: "man", age: 10 },
        { id: "id_043", name: "mack", sex: "man" },
        { id: "id_044", name: "mack", sex: "man", age: 5 },
        { id: "id_045", name: "mack", sex: "man", age: 5 },
        { id: "id_046", name: "mack", sex: "man", age: 10 },
        { id: "id_047", name: "mack", sex: "man", age: 10 },
        { id: "id_048", name: "mack", sex: "man", age: 10 },
        { id: "id_049", name: "mack", sex: "man", age: 10 },
        { id: "id_050", name: "mack", sex: "man", age: 10 },
        { id: "id_051", name: "mack", sex: "man", age: 10 },
        { id: "id_052", name: "jack", sex: "man", age: 10 },
        { id: "id_053", name: "mack", sex: "man" },
        { id: "id_054", name: "mack", sex: "man", age: 5 },
        { id: "id_055", name: "mack", sex: "man", age: 5 },
        { id: "id_056", name: "mack", sex: "man", age: 10 },
        { id: "id_057", name: "mack", sex: "man", age: 10 },
        { id: "id_058", name: "mack", sex: "man", age: 10 },
        { id: "id_059", name: "mack", sex: "man", age: 10 },
        { id: "id_060", name: "mack", sex: "man", age: 10 },
        { id: "id_061", name: "mack", sex: "man", age: 10 },
        { id: "id_062", name: "jack", sex: "man", age: 10 },
        { id: "id_063", name: "mack", sex: "man" },
        { id: "id_064", name: "mack", sex: "man", age: 5 },
        { id: "id_065", name: "mack", sex: "man", age: 5 },
        { id: "id_066", name: "mack", sex: "man", age: 10 },
        { id: "id_067", name: "mack", sex: "man", age: 10 },
        { id: "id_068", name: "mack", sex: "man", age: 10 },
        { id: "id_069", name: "mack", sex: "man", age: 10 },
        { id: "id_070", name: "mack", sex: "man", age: 10 },
        { id: "id_071", name: "mack", sex: "man", age: 10 },
        { id: "id_072", name: "jack", sex: "man", age: 10 },
        { id: "id_073", name: "mack", sex: "man" },
        { id: "id_074", name: "mack", sex: "man", age: 5 },
        { id: "id_075", name: "mack", sex: "man", age: 5 },
        { id: "id_076", name: "mack", sex: "man", age: 10 },
        { id: "id_077", name: "mack", sex: "man", age: 10 },
        { id: "id_078", name: "mack", sex: "man", age: 10 },
        { id: "id_079", name: "mack", sex: "man", age: 10 },
        { id: "id_080", name: "mack", sex: "man", age: 10 },
        { id: "id_081", name: "mack", sex: "man", age: 10 },
        { id: "id_082", name: "jack", sex: "man", age: 10 },
        { id: "id_083", name: "mack", sex: "man" },
        { id: "id_084", name: "mack", sex: "man", age: 5 },
        { id: "id_085", name: "mack", sex: "man", age: 5 },
        { id: "id_086", name: "mack", sex: "man", age: 10 },
        { id: "id_087", name: "mack", sex: "man", age: 10 },
        { id: "id_088", name: "mack", sex: "man", age: 10 },
        { id: "id_089", name: "mack", sex: "man", age: 10 },
        { id: "id_090", name: "mack", sex: "man", age: 10 },
        { id: "id_091", name: "mack", sex: "man", age: 10 },
        { id: "id_092", name: "jack", sex: "man", age: 10 },
        { id: "id_093", name: "mack", sex: "man" },
        { id: "id_094", name: "mack", sex: "man", age: 5 },
        { id: "id_095", name: "mack", sex: "man", age: 5 },
        { id: "id_096", name: "mack", sex: "man", age: 10 },
        { id: "id_097", name: "mack", sex: "man", age: 10 },
        { id: "id_098", name: "mack", sex: "man", age: 10 },
        { id: "id_099", name: "mack", sex: "man", age: 10 },
        { id: "id_100", name: "mack", sex: "man", age: 10 },
        { id: "id_101", name: "mack", sex: "man", age: 10 },
        { id: "id_102", name: "jack", sex: "man", age: 10 },
        { id: "id_103", name: "mack", sex: "man" },
        { id: "id_104", name: "mack", sex: "man", age: 5 },
        { id: "id_105", name: "mack", sex: "man", age: 5 },
        { id: "id_106", name: "mack", sex: "man", age: 10 },
        { id: "id_107", name: "mack", sex: "man", age: 10 },
        { id: "id_108", name: "mack", sex: "man", age: 10 },
        { id: "id_109", name: "mack", sex: "man", age: 10 },
        { id: "id_110", name: "mack", sex: "man", age: 10 },
        { id: "id_111", name: "mack", sex: "man", age: 10 },
        { id: "id_112", name: "jack", sex: "man", age: 10 },
        { id: "id_113", name: "mack", sex: "man" },
        { id: "id_114", name: "mack", sex: "man", age: 5 },
        { id: "id_115", name: "mack", sex: "man", age: 5 },
        { id: "id_116", name: "mack", sex: "man", age: 10 },
        { id: "id_117", name: "mack", sex: "man", age: 10 },
        { id: "id_118", name: "mack", sex: "man", age: 10 },
        { id: "id_119", name: "mack", sex: "man", age: 10 },
        { id: "id_120", name: "mack", sex: "man", age: 10 },
        { id: "id_121", name: "mack", sex: "man", age: 10 },
        { id: "id_122", name: "jack", sex: "man", age: 10 },
        { id: "id_123", name: "mack", sex: "man" },
        { id: "id_124", name: "mack", sex: "man", age: 5 },
        { id: "id_125", name: "mack", sex: "man", age: 5 },
        { id: "id_126", name: "mack", sex: "man", age: 10 },
        { id: "id_127", name: "mack", sex: "man", age: 10 },
        { id: "id_128", name: "mack", sex: "man", age: 10 },
        { id: "id_129", name: "mack", sex: "man", age: 10 },
        { id: "id_130", name: "mack", sex: "man", age: 10 },
        { id: "id_131", name: "mack", sex: "man", age: 10 },
        { id: "id_132", name: "jack", sex: "man", age: 10 },
        { id: "id_133", name: "mack", sex: "man" },
        { id: "id_134", name: "mack", sex: "man", age: 5 },
        { id: "id_135", name: "mack", sex: "man", age: 5 },
        { id: "id_136", name: "mack", sex: "man", age: 10 },
        { id: "id_137", name: "mack", sex: "man", age: 10 },
        { id: "id_138", name: "mack", sex: "man", age: 10 },
        { id: "id_139", name: "mack", sex: "man", age: 10 },
        { id: "id_140", name: "mack", sex: "man", age: 10 },
        { id: "id_141", name: "mack", sex: "man", age: 10 },
        { id: "id_142", name: "jack", sex: "man", age: 10 },
        { id: "id_143", name: "mack", sex: "man" },
        { id: "id_144", name: "mack", sex: "man", age: 5 },
        { id: "id_145", name: "mack", sex: "man", age: 5 },
        { id: "id_146", name: "mack", sex: "man", age: 10 },
        { id: "id_147", name: "mack", sex: "man", age: 10 },
        { id: "id_148", name: "mack", sex: "man", age: 10 },
        { id: "id_149", name: "mack", sex: "man", age: 10 },
        { id: "id_150", name: "mack", sex: "man", age: 10 },
        { id: "id_151", name: "mack", sex: "man", age: 10 },
        { id: "id_152", name: "jack", sex: "man", age: 10 },
        { id: "id_153", name: "mack", sex: "man" },
        { id: "id_154", name: "mack", sex: "man", age: 5 },
        { id: "id_155", name: "mack", sex: "man", age: 5 },
        { id: "id_156", name: "mack", sex: "man", age: 10 },
        { id: "id_157", name: "mack", sex: "man", age: 10 },
        { id: "id_158", name: "mack", sex: "man", age: 10 },
        { id: "id_159", name: "mack", sex: "man", age: 10 },
        { id: "id_160", name: "mack", sex: "man", age: 10 },
        { id: "id_161", name: "mack", sex: "man", age: 10 },
        { id: "id_162", name: "jack", sex: "man", age: 10 },
        { id: "id_163", name: "mack", sex: "man" },
        { id: "id_164", name: "mack", sex: "man", age: 5 },
        { id: "id_165", name: "mack", sex: "man", age: 5 },
        { id: "id_166", name: "mack", sex: "man", age: 10 },
        { id: "id_167", name: "mack", sex: "man", age: 10 },
        { id: "id_168", name: "mack", sex: "man", age: 10 },
        { id: "id_169", name: "mack", sex: "man", age: 10 },
        { id: "id_170", name: "mack", sex: "man", age: 10 },
        { id: "id_171", name: "mack", sex: "man", age: 10 },
        { id: "id_172", name: "jack", sex: "man", age: 10 },
        { id: "id_173", name: "mack", sex: "man" },
        { id: "id_174", name: "mack", sex: "man", age: 5 },
        { id: "id_175", name: "mack", sex: "man", age: 5 },
        { id: "id_176", name: "mack", sex: "man", age: 10 },
        { id: "id_177", name: "mack", sex: "man", age: 10 },
        { id: "id_178", name: "mack", sex: "man", age: 10 },
        { id: "id_179", name: "mack", sex: "man", age: 10 },
        { id: "id_180", name: "mack", sex: "man", age: 10 },
        { id: "id_181", name: "mack", sex: "man", age: 10 },
        { id: "id_182", name: "jack", sex: "man", age: 10 },
        { id: "id_183", name: "mack", sex: "man" },
        { id: "id_184", name: "mack", sex: "man", age: 5 },
        { id: "id_185", name: "mack", sex: "man", age: 5 },
        { id: "id_186", name: "mack", sex: "man", age: 10 },
        { id: "id_187", name: "mack", sex: "man", age: 10 },
        { id: "id_188", name: "mack", sex: "man", age: 10 },
        { id: "id_189", name: "mack", sex: "man", age: 10 },
        { id: "id_190", name: "mack", sex: "man", age: 10 },
        { id: "id_191", name: "mack", sex: "man", age: 10 },
        { id: "id_192", name: "jack", sex: "man", age: 10 },
        { id: "id_193", name: "mack", sex: "man" },
        { id: "id_194", name: "mack", sex: "man", age: 5 },
        { id: "id_195", name: "mack", sex: "man", age: 5 },
        { id: "id_196", name: "mack", sex: "man", age: 10 },
        { id: "id_197", name: "mack", sex: "man", age: 10 },
        { id: "id_198", name: "mack", sex: "man", age: 10 },
        { id: "id_199", name: "mack", sex: "man", age: 10 },
        { id: "id_200", name: "mack", sex: "man", age: 10 },
        { id: "id_201", name: "mack", sex: "man", age: 10 },
        { id: "id_202", name: "jack", sex: "man", age: 10 },
        { id: "id_203", name: "mack", sex: "man" },
        { id: "id_204", name: "mack", sex: "man", age: 5 },
        { id: "id_205", name: "mack", sex: "man", age: 5 },
        { id: "id_206", name: "mack", sex: "man", age: 10 },
        { id: "id_207", name: "mack", sex: "man", age: 10 },
        { id: "id_208", name: "mack", sex: "man", age: 10 },
        { id: "id_209", name: "mack", sex: "man", age: 10 },
        { id: "id_210", name: "mack", sex: "man", age: 10 },
        { id: "id_211", name: "mack", sex: "man", age: 10 },
        { id: "id_212", name: "jack", sex: "man", age: 10 },
        { id: "id_213", name: "mack", sex: "man" },
        { id: "id_214", name: "mack", sex: "man", age: 5 },
        { id: "id_215", name: "mack", sex: "man", age: 5 },
        { id: "id_216", name: "mack", sex: "man", age: 10 },
        { id: "id_217", name: "mack", sex: "man", age: 10 },
        { id: "id_218", name: "mack", sex: "man", age: 10 },
        { id: "id_219", name: "mack", sex: "man", age: 10 },
        { id: "id_220", name: "mack", sex: "man", age: 10 },
        { id: "id_221", name: "mack", sex: "man", age: 10 },
        { id: "id_222", name: "jack", sex: "man", age: 10 },
        { id: "id_223", name: "mack", sex: "man" },
        { id: "id_224", name: "mack", sex: "man", age: 5 },
        { id: "id_225", name: "mack", sex: "man", age: 5 },
        { id: "id_226", name: "mack", sex: "man", age: 10 },
        { id: "id_227", name: "mack", sex: "man", age: 10 },
        { id: "id_228", name: "mack", sex: "man", age: 10 },
        { id: "id_229", name: "mack", sex: "man", age: 10 },
        { id: "id_230", name: "mack", sex: "man", age: 10 },
        { id: "id_231", name: "mack", sex: "man", age: 10 },
        { id: "id_232", name: "jack", sex: "man", age: 10 },
        { id: "id_233", name: "mack", sex: "man" },
        { id: "id_234", name: "mack", sex: "man", age: 5 },
        { id: "id_235", name: "mack", sex: "man", age: 5 },
        { id: "id_236", name: "mack", sex: "man", age: 10 },
        { id: "id_237", name: "mack", sex: "man", age: 10 },
        { id: "id_238", name: "mack", sex: "man", age: 10 },
        { id: "id_239", name: "mack", sex: "man", age: 10 },
        { id: "id_240", name: "mack", sex: "man", age: 10 },
        { id: "id_241", name: "mack", sex: "man", age: 10 },
        { id: "id_242", name: "jack", sex: "man", age: 10 },
        { id: "id_243", name: "mack", sex: "man" },
        { id: "id_244", name: "mack", sex: "man", age: 5 },
        { id: "id_245", name: "mack", sex: "man", age: 5 },
        { id: "id_246", name: "mack", sex: "man", age: 10 },
        { id: "id_247", name: "mack", sex: "man", age: 10 },
        { id: "id_248", name: "mack", sex: "man", age: 10 },
        { id: "id_249", name: "mack", sex: "man", age: 10 },
        { id: "id_250", name: "mack", sex: "man", age: 10 },
        { id: "id_251", name: "mack", sex: "man", age: 10 },
        { id: "id_252", name: "jack", sex: "man", age: 10 },
        { id: "id_253", name: "mack", sex: "man" },
        { id: "id_254", name: "mack", sex: "man", age: 5 },
        { id: "id_255", name: "mack", sex: "man", age: 5 },
        { id: "id_256", name: "mack", sex: "man", age: 10 },
        { id: "id_257", name: "mack", sex: "man", age: 10 },
        { id: "id_258", name: "mack", sex: "man", age: 10 },
        { id: "id_259", name: "mack", sex: "man", age: 10 },
        { id: "id_260", name: "mack", sex: "man", age: 10 },
        { id: "id_261", name: "mack", sex: "man", age: 10 },
        { id: "id_262", name: "jack", sex: "man", age: 10 },
        { id: "id_263", name: "mack", sex: "man" },
        { id: "id_264", name: "mack", sex: "man", age: 5 },
        { id: "id_265", name: "mack", sex: "man", age: 5 },
        { id: "id_266", name: "mack", sex: "man", age: 10 },
        { id: "id_267", name: "mack", sex: "man", age: 10 },
        { id: "id_268", name: "mack", sex: "man", age: 10 },
        { id: "id_269", name: "mack", sex: "man", age: 10 },
        { id: "id_270", name: "mack", sex: "man", age: 10 },
        { id: "id_271", name: "mack", sex: "man", age: 10 },
        { id: "id_272", name: "jack", sex: "man", age: 10 },
        { id: "id_273", name: "mack", sex: "man" },
        { id: "id_274", name: "mack", sex: "man", age: 5 },
        { id: "id_275", name: "mack", sex: "man", age: 5 },
        { id: "id_276", name: "mack", sex: "man", age: 10 },
        { id: "id_277", name: "mack", sex: "man", age: 10 },
        { id: "id_278", name: "mack", sex: "man", age: 10 },
        { id: "id_279", name: "mack", sex: "man", age: 10 },
        { id: "id_280", name: "mack", sex: "man", age: 10 },
        { id: "id_281", name: "mack", sex: "man", age: 10 },
        { id: "id_282", name: "jack", sex: "man", age: 10 },
        { id: "id_283", name: "mack", sex: "man" },
        { id: "id_284", name: "mack", sex: "man", age: 5 },
        { id: "id_285", name: "mack", sex: "man", age: 5 },
        { id: "id_286", name: "mack", sex: "man", age: 10 },
        { id: "id_287", name: "mack", sex: "man", age: 10 },
        { id: "id_288", name: "mack", sex: "man", age: 10 },
        { id: "id_289", name: "mack", sex: "man", age: 10 },
        { id: "id_290", name: "mack", sex: "man", age: 10 },
        { id: "id_291", name: "mack", sex: "man", age: 10 },
        { id: "id_292", name: "jack", sex: "man", age: 10 },
        { id: "id_293", name: "mack", sex: "man" },
        { id: "id_294", name: "mack", sex: "man", age: 5 },
        { id: "id_295", name: "mack", sex: "man", age: 5 },
        { id: "id_296", name: "mack", sex: "man", age: 10 },
        { id: "id_297", name: "mack", sex: "man", age: 10 },
        { id: "id_298", name: "mack", sex: "man", age: 10 },
        { id: "id_299", name: "mack", sex: "man", age: 10 },
        { id: "id_300", name: "mack", sex: "man", age: 10 },
        { id: "id_301", name: "mack", sex: "man", age: 10 },
        { id: "id_302", name: "jack", sex: "man", age: 10 },
        { id: "id_303", name: "mack", sex: "man" },
        { id: "id_304", name: "mack", sex: "man", age: 5 },
        { id: "id_305", name: "mack", sex: "man", age: 5 },
        { id: "id_306", name: "mack", sex: "man", age: 10 },
        { id: "id_307", name: "mack", sex: "man", age: 10 },
        { id: "id_308", name: "mack", sex: "man", age: 10 },
        { id: "id_309", name: "mack", sex: "man", age: 10 },
        { id: "id_310", name: "mack", sex: "man", age: 10 },
        { id: "id_311", name: "mack", sex: "man", age: 10 },
        { id: "id_312", name: "jack", sex: "man", age: 10 },
        { id: "id_313", name: "mack", sex: "man" },
        { id: "id_314", name: "mack", sex: "man", age: 5 },
        { id: "id_315", name: "mack", sex: "man", age: 5 },
        { id: "id_316", name: "mack", sex: "man", age: 10 },
        { id: "id_317", name: "mack", sex: "man", age: 10 },
        { id: "id_318", name: "mack", sex: "man", age: 10 },
        { id: "id_319", name: "mack", sex: "man", age: 10 },
        { id: "id_320", name: "mack", sex: "man", age: 10 },
        { id: "id_321", name: "mack", sex: "man", age: 10 },
        { id: "id_322", name: "jack", sex: "man", age: 10 },
        { id: "id_323", name: "mack", sex: "man" },
        { id: "id_324", name: "mack", sex: "man", age: 5 },
        { id: "id_325", name: "mack", sex: "man", age: 5 },
        { id: "id_326", name: "mack", sex: "man", age: 10 },
        { id: "id_327", name: "mack", sex: "man", age: 10 },
        { id: "id_328", name: "mack", sex: "man", age: 10 },
        { id: "id_329", name: "mack", sex: "man", age: 10 },
        { id: "id_330", name: "mack", sex: "man", age: 10 },
        { id: "id_331", name: "mack", sex: "man", age: 10 },
        { id: "id_332", name: "jack", sex: "man", age: 10 },
        { id: "id_333", name: "mack", sex: "man" },
        { id: "id_334", name: "mack", sex: "man", age: 5 },
        { id: "id_335", name: "mack", sex: "man", age: 5 },
        { id: "id_336", name: "mack", sex: "man", age: 10 },
        { id: "id_337", name: "mack", sex: "man", age: 10 },
        { id: "id_338", name: "mack", sex: "man", age: 10 },
        { id: "id_339", name: "mack", sex: "man", age: 10 },
      ]
    };
  }
};
</script>
