<template>
  <b-grid-view
    table-striped
    table-hover
    thead-sticky
    table-bordered
    fixedSize="sm"
    fixed="4"
    thead-theme="dark"
    :list="list"
    :head="head"
    :operate="operate"
    :row-style="rowStyle"
  />
</template>

<script>
import BGridView from "@/components/content/GridView/b-grid-view.vue";

export default {
  name: "BGridViewDemo",
  components: { BGridView },
  data() {
    return {
      head: [
        {
          icon: "hash",
          field: "_serial",
          colStyle: 'width: 35px;',
          canNotSort: true,
        },
        {
          label: "id",
          field: "id",
          colClass: "bg-info",
          colStyle: "width: 35px;"
        },
        {
          label: "name",
          field: "name",
          colStyle: "width: 100px;",
          format: value => "name_" + value
        },
        { label: "sex", field: "sex", colStyle: "width: 100px;" },
        {
          label: "age",
          field: "age",
          colStyle: "width: 58px;",
          cellStyle: value => {
            return { class: Number(value) ? "bg-success" : "bg-danger" };
          }
        },
        {
          label: "1",
          field: "1",
          children: [
            {
              label: "1-1",
              field: "1-1",
              children: [
                { label: "1-1-1", field: "1-1-1" },
                { label: "1-1-2", field: "1-1-2" }
              ]
            },
            { label: "1-2", field: "1-2" },
            {
              label: "1-3",
              field: "1-3",
              children: [
                { label: "1-3-1", field: "1-3-1" },
                { label: "1-3-2", field: "1-3-2" }
              ]
            }
          ]
        },
        {
          label: "2",
          field: "2",
          children: [
            {
              label: "2-1",
              field: "2-1",
              children: [
                { label: "2-1-1", field: "2-1-1" },
                { label: "2-1-2", field: "2-1-2" }
              ]
            },
            {
              label: "2-2",
              field: "2-2",
              children: [
                { label: "2-2-1", field: "2-2-1" },
                { label: "2-2-2", field: "2-2-2" }
              ]
            },
            { label: "2-3", field: "2-3" }
          ]
        }
      ],
      operate: {
        index: 2,
        value: ["check", "view", "edit", "delete", "flow"]
      },
      rowStyle: {
        class: function(row) {
          if (row && row.age && Number(row.age) == 5) return "text-warning";
        }
      },
      sort: ["sex", "2-1-1", "2-2-2"],
      list: [
        { id: "id_1", name: "mack", sex: "man", age: 10 },
        { id: "id_2", name: "jack", sex: "man", age: 10 },
        { id: "id_3", name: "mack", sex: "man" },
        { id: "id_4", name: "mack", sex: "man", age: 5 },
        { id: "id_5", name: "mack", sex: "man", age: 5 },
        { id: "id_6", name: "mack", sex: "man", age: 10 },
        { id: "id_7", name: "mack", sex: "man", age: 10 },
        { id: "id_8", name: "mack", sex: "man", age: 10 },
        { id: "id_9", name: "mack", sex: "man", age: 10 },
        { id: "id_3", name: "mack", sex: "man" },
        { id: "id_4", name: "mack", sex: "man", age: 10 },
        { id: "id_5", name: "mack", sex: "man", age: 10 },
        { id: "id_6", name: "mack", sex: "man", age: 10 },
        { id: "id_7", name: "mack", sex: "man", age: 10 },
        { id: "id_8", name: "mack", sex: "man", age: 10 },
        { id: "id_9", name: "mack", sex: "man", age: 10 },
        { id: "id_3", name: "mack", sex: "man" },
        { id: "id_4", name: "mack", sex: "man", age: 10 },
        { id: "id_5", name: "mack", sex: "man", age: 10 },
        { id: "id_6", name: "mack", sex: "man", age: 10 },
        { id: "id_7", name: "mack", sex: "man", age: 10 },
        { id: "id_8", name: "mack", sex: "man", age: 10 },
        { id: "id_9", name: "mack", sex: "man", age: 10 },
        { id: "id_3", name: "mack", sex: "man" },
        { id: "id_4", name: "mack", sex: "man", age: 10 },
        { id: "id_5", name: "mack", sex: "man", age: 10 },
        { id: "id_6", name: "mack", sex: "man", age: 10 },
        { id: "id_7", name: "mack", sex: "man", age: 10 },
        { id: "id_8", name: "mack", sex: "man", age: 10 },
        { id: "id_9", name: "mack", sex: "man", age: 10 },
        { id: "id_3", name: "mack", sex: "man" },
        { id: "id_4", name: "mack", sex: "man", age: 10 },
        { id: "id_5", name: "mack", sex: "man", age: 10 },
        { id: "id_6", name: "mack", sex: "man", age: 10 },
        { id: "id_7", name: "mack", sex: "man", age: 10 },
        { id: "id_8", name: "mack", sex: "man", age: 10 },
        { id: "id_9", name: "mack", sex: "man", age: 10 },
        { id: "id_3", name: "mack", sex: "man" },
        { id: "id_4", name: "mack", sex: "man", age: 10 },
        { id: "id_5", name: "mack", sex: "man", age: 10 },
        { id: "id_6", name: "mack", sex: "man", age: 10 },
        { id: "id_7", name: "mack", sex: "man", age: 10 },
        { id: "id_8", name: "mack", sex: "man", age: 10 },
        { id: "id_9", name: "mack", sex: "man", age: 10 },
        { id: "id_3", name: "mack", sex: "man" },
        { id: "id_4", name: "mack", sex: "man", age: 10 },
        { id: "id_5", name: "mack", sex: "man", age: 10 },
        { id: "id_6", name: "mack", sex: "man", age: 10 },
        { id: "id_7", name: "mack", sex: "man", age: 10 },
        { id: "id_8", name: "mack", sex: "man", age: 10 },
        { id: "id_9", name: "mack", sex: "man", age: 10 },
        { id: "id_3", name: "mack", sex: "man" },
        { id: "id_4", name: "mack", sex: "man", age: 10 },
        { id: "id_5", name: "mack", sex: "man", age: 10 },
        { id: "id_6", name: "mack", sex: "man", age: 10 },
        { id: "id_7", name: "mack", sex: "man", age: 10 },
        { id: "id_8", name: "mack", sex: "man", age: 10 },
        { id: "id_9", name: "mack", sex: "man", age: 10 },
        { id: "id_3", name: "mack", sex: "man" },
        { id: "id_4", name: "mack", sex: "man", age: 10 },
        { id: "id_5", name: "mack", sex: "man", age: 10 },
        { id: "id_6", name: "mack", sex: "man", age: 10 },
        { id: "id_7", name: "mack", sex: "man", age: 10 },
        { id: "id_8", name: "mack", sex: "man", age: 10 },
        { id: "id_9", name: "mack", sex: "man", age: 10 },
        { id: "id_3", name: "mack", sex: "man" },
        { id: "id_4", name: "mack", sex: "man", age: 10 },
        { id: "id_5", name: "mack", sex: "man", age: 10 },
        { id: "id_6", name: "mack", sex: "man", age: 10 },
        { id: "id_7", name: "mack", sex: "man", age: 10 },
        { id: "id_8", name: "mack", sex: "man", age: 10 },
        { id: "id_9", name: "mack", sex: "man", age: 10 },
        { id: "id_3", name: "mack", sex: "man" },
        { id: "id_4", name: "mack", sex: "man", age: 10 },
        { id: "id_5", name: "mack", sex: "man", age: 10 },
        { id: "id_6", name: "mack", sex: "man", age: 10 },
        { id: "id_7", name: "mack", sex: "man", age: 10 },
        { id: "id_8", name: "mack", sex: "man", age: 10 },
        { id: "id_9", name: "mack", sex: "man", age: 10 },
        { id: "id_3", name: "mack", sex: "man" },
        { id: "id_4", name: "mack", sex: "man", age: 10 },
        { id: "id_5", name: "mack", sex: "man", age: 10 },
        { id: "id_6", name: "mack", sex: "man", age: 10 },
        { id: "id_7", name: "mack", sex: "man", age: 10 },
        { id: "id_8", name: "mack", sex: "man", age: 10 },
        { id: "id_9", name: "mack", sex: "man", age: 10 },
        { id: "id_3", name: "mack", sex: "man" },
        { id: "id_4", name: "mack", sex: "man", age: 10 },
        { id: "id_5", name: "mack", sex: "man", age: 10 },
        { id: "id_6", name: "mack", sex: "man", age: 10 },
        { id: "id_7", name: "mack", sex: "man", age: 10 },
        { id: "id_8", name: "mack", sex: "man", age: 10 },
        { id: "id_9", name: "mack", sex: "man", age: 10 },
        { id: "id_3", name: "mack", sex: "man" },
        { id: "id_4", name: "mack", sex: "man", age: 10 },
        { id: "id_5", name: "mack", sex: "man", age: 10 },
        { id: "id_6", name: "mack", sex: "man", age: 10 },
        { id: "id_7", name: "mack", sex: "man", age: 10 },
        { id: "id_8", name: "mack", sex: "man", age: 10 },
        { id: "id_9", name: "mack", sex: "man", age: 10 },
        { id: "id_3", name: "mack", sex: "man" },
        { id: "id_4", name: "mack", sex: "man", age: 10 },
        { id: "id_5", name: "mack", sex: "man", age: 10 },
        { id: "id_6", name: "mack", sex: "man", age: 10 },
        { id: "id_7", name: "mack", sex: "man", age: 10 },
        { id: "id_8", name: "mack", sex: "man", age: 10 },
        { id: "id_9", name: "mack", sex: "man", age: 10 },
        { id: "id_3", name: "mack", sex: "man" },
        { id: "id_4", name: "mack", sex: "man", age: 10 },
        { id: "id_5", name: "mack", sex: "man", age: 10 },
        { id: "id_6", name: "mack", sex: "man", age: 10 },
        { id: "id_7", name: "mack", sex: "man", age: 10 },
        { id: "id_8", name: "mack", sex: "man", age: 10 },
        { id: "id_9", name: "mack", sex: "man", age: 10 },
        { id: "id_3", name: "mack", sex: "man" },
        { id: "id_4", name: "mack", sex: "man", age: 10 },
        { id: "id_5", name: "mack", sex: "man", age: 10 },
        { id: "id_6", name: "mack", sex: "man", age: 10 },
        { id: "id_7", name: "mack", sex: "man", age: 10 },
        { id: "id_8", name: "mack", sex: "man", age: 10 },
        { id: "id_9", name: "mack", sex: "man", age: 10 },
        { id: "id_3", name: "mack", sex: "man" },
        { id: "id_4", name: "mack", sex: "man", age: 10 },
        { id: "id_5", name: "mack", sex: "man", age: 10 },
        { id: "id_6", name: "mack", sex: "man", age: 10 },
        { id: "id_7", name: "mack", sex: "man", age: 10 },
        { id: "id_8", name: "mack", sex: "man", age: 10 },
        { id: "id_9", name: "mack", sex: "man", age: 10 },
        { id: "id_3", name: "mack", sex: "man" },
        { id: "id_4", name: "mack", sex: "man", age: 10 },
        { id: "id_5", name: "mack", sex: "man", age: 10 },
        { id: "id_6", name: "mack", sex: "man", age: 10 },
        { id: "id_7", name: "mack", sex: "man", age: 10 },
        { id: "id_8", name: "mack", sex: "man", age: 10 },
        { id: "id_9", name: "mack", sex: "man", age: 10 },
        { id: "id_3", name: "mack", sex: "man" },
        { id: "id_4", name: "mack", sex: "man", age: 10 },
        { id: "id_5", name: "mack", sex: "man", age: 10 },
        { id: "id_6", name: "mack", sex: "man", age: 10 },
        { id: "id_7", name: "mack", sex: "man", age: 10 },
        { id: "id_8", name: "mack", sex: "man", age: 10 },
        { id: "id_9", name: "mack", sex: "man", age: 10 },
        { id: "id_3", name: "mack", sex: "man" },
        { id: "id_4", name: "mack", sex: "man", age: 10 },
        { id: "id_5", name: "mack", sex: "man", age: 10 },
        { id: "id_6", name: "mack", sex: "man", age: 10 },
        { id: "id_7", name: "mack", sex: "man", age: 10 },
        { id: "id_8", name: "mack", sex: "man", age: 10 },
        { id: "id_9", name: "mack", sex: "man", age: 10 },
        { id: "id_3", name: "mack", sex: "man" },
        { id: "id_4", name: "mack", sex: "man", age: 10 },
        { id: "id_5", name: "mack", sex: "man", age: 10 },
        { id: "id_6", name: "mack", sex: "man", age: 10 },
        { id: "id_7", name: "mack", sex: "man", age: 10 },
        { id: "id_8", name: "mack", sex: "man", age: 10 },
        { id: "id_9", name: "mack", sex: "man", age: 10 },
        { id: "id_3", name: "mack", sex: "man" },
        { id: "id_4", name: "mack", sex: "man", age: 10 },
        { id: "id_5", name: "mack", sex: "man", age: 10 },
        { id: "id_6", name: "mack", sex: "man", age: 10 },
        { id: "id_7", name: "mack", sex: "man", age: 10 },
        { id: "id_8", name: "mack", sex: "man", age: 10 },
        { id: "id_9", name: "mack", sex: "man", age: 10 },
        { id: "id_3", name: "mack", sex: "man" },
        { id: "id_4", name: "mack", sex: "man", age: 10 },
        { id: "id_5", name: "mack", sex: "man", age: 10 },
        { id: "id_6", name: "mack", sex: "man", age: 10 },
        { id: "id_7", name: "mack", sex: "man", age: 10 },
        { id: "id_8", name: "mack", sex: "man", age: 10 },
        { id: "id_9", name: "mack", sex: "man", age: 10 },
        { id: "id_3", name: "mack", sex: "man" },
        { id: "id_4", name: "mack", sex: "man", age: 10 },
        { id: "id_5", name: "mack", sex: "man", age: 10 },
        { id: "id_6", name: "mack", sex: "man", age: 10 },
        { id: "id_7", name: "mack", sex: "man", age: 10 },
        { id: "id_8", name: "mack", sex: "man", age: 10 },
        { id: "id_9", name: "mack", sex: "man", age: 10 },
        { id: "id_3", name: "mack", sex: "man" },
        { id: "id_4", name: "mack", sex: "man", age: 10 },
        { id: "id_5", name: "mack", sex: "man", age: 10 },
        { id: "id_6", name: "mack", sex: "man", age: 10 },
        { id: "id_7", name: "mack", sex: "man", age: 10 },
        { id: "id_8", name: "mack", sex: "man", age: 10 },
        { id: "id_9", name: "mack", sex: "man", age: 10 },
        { id: "id_3", name: "mack", sex: "man" },
        { id: "id_4", name: "mack", sex: "man", age: 10 },
        { id: "id_5", name: "mack", sex: "man", age: 10 },
        { id: "id_6", name: "mack", sex: "man", age: 10 },
        { id: "id_7", name: "mack", sex: "man", age: 10 },
        { id: "id_8", name: "mack", sex: "man", age: 10 },
        { id: "id_9", name: "mack", sex: "man", age: 10 },
        { id: "id_3", name: "mack", sex: "man" },
        { id: "id_4", name: "mack", sex: "man", age: 10 },
        { id: "id_5", name: "mack", sex: "man", age: 10 },
        { id: "id_6", name: "mack", sex: "man", age: 10 },
        { id: "id_7", name: "mack", sex: "man", age: 10 },
        { id: "id_8", name: "mack", sex: "man", age: 10 },
        { id: "id_9", name: "mack", sex: "man", age: 10 },
        { id: "id_3", name: "mack", sex: "man" },
        { id: "id_4", name: "mack", sex: "man", age: 10 },
        { id: "id_5", name: "mack", sex: "man", age: 10 },
        { id: "id_6", name: "mack", sex: "man", age: 10 },
        { id: "id_7", name: "mack", sex: "man", age: 10 },
        { id: "id_8", name: "mack", sex: "man", age: 10 },
        { id: "id_9", name: "mack", sex: "man", age: 10 },
        { id: "id_3", name: "mack", sex: "man" },
        { id: "id_4", name: "mack", sex: "man", age: 10 },
        { id: "id_5", name: "mack", sex: "man", age: 10 },
        { id: "id_6", name: "mack", sex: "man", age: 10 },
        { id: "id_7", name: "mack", sex: "man", age: 10 },
        { id: "id_8", name: "mack", sex: "man", age: 10 },
        { id: "id_9", name: "mack", sex: "man", age: 10 },
        { id: "id_3", name: "mack", sex: "man" },
        { id: "id_4", name: "mack", sex: "man", age: 10 },
        { id: "id_5", name: "mack", sex: "man", age: 10 },
        { id: "id_6", name: "mack", sex: "man", age: 10 },
        { id: "id_7", name: "mack", sex: "man", age: 10 },
        { id: "id_8", name: "mack", sex: "man", age: 10 },
        { id: "id_9", name: "mack", sex: "man", age: 10 },
        { id: "id_3", name: "mack", sex: "man" },
        { id: "id_4", name: "mack", sex: "man", age: 10 },
        { id: "id_5", name: "mack", sex: "man", age: 10 },
        { id: "id_6", name: "mack", sex: "man", age: 10 },
        { id: "id_7", name: "mack", sex: "man", age: 10 },
        { id: "id_8", name: "mack", sex: "man", age: 10 },
        { id: "id_9", name: "mack", sex: "man", age: 10 },
        { id: "id_3", name: "mack", sex: "man" },
        { id: "id_4", name: "mack", sex: "man", age: 10 },
        { id: "id_5", name: "mack", sex: "man", age: 10 },
        { id: "id_6", name: "mack", sex: "man", age: 10 },
        { id: "id_7", name: "mack", sex: "man", age: 10 },
        { id: "id_8", name: "mack", sex: "man", age: 10 },
        { id: "id_9", name: "mack", sex: "man", age: 10 },
        { id: "id_3", name: "mack", sex: "man" },
        { id: "id_4", name: "mack", sex: "man", age: 10 },
        { id: "id_5", name: "mack", sex: "man", age: 10 },
        { id: "id_6", name: "mack", sex: "man", age: 10 },
        { id: "id_7", name: "mack", sex: "man", age: 10 },
        { id: "id_8", name: "mack", sex: "man", age: 10 },
        { id: "id_9", name: "mack", sex: "man", age: 10 },
        { id: "id_3", name: "mack", sex: "man" },
        { id: "id_4", name: "mack", sex: "man", age: 10 },
        { id: "id_5", name: "mack", sex: "man", age: 10 },
        { id: "id_6", name: "mack", sex: "man", age: 10 },
        { id: "id_7", name: "mack", sex: "man", age: 10 },
        { id: "id_8", name: "mack", sex: "man", age: 10 },
        { id: "id_9", name: "mack", sex: "man", age: 10 },
        { id: "id_3", name: "mack", sex: "man" },
        { id: "id_4", name: "mack", sex: "man", age: 10 },
        { id: "id_5", name: "mack", sex: "man", age: 10 },
        { id: "id_6", name: "mack", sex: "man", age: 10 },
        { id: "id_7", name: "mack", sex: "man", age: 10 },
        { id: "id_8", name: "mack", sex: "man", age: 10 },
        { id: "id_9", name: "mack", sex: "man", age: 10 },
        { id: "id_3", name: "mack", sex: "man" },
        { id: "id_4", name: "mack", sex: "man", age: 10 },
        { id: "id_5", name: "mack", sex: "man", age: 10 },
        { id: "id_6", name: "mack", sex: "man", age: 10 },
        { id: "id_7", name: "mack", sex: "man", age: 10 },
        { id: "id_8", name: "mack", sex: "man", age: 10 },
        { id: "id_9", name: "mack", sex: "man", age: 10 },
        { id: "id_3", name: "mack", sex: "man" },
        { id: "id_4", name: "mack", sex: "man", age: 10 },
        { id: "id_5", name: "mack", sex: "man", age: 10 },
        { id: "id_6", name: "mack", sex: "man", age: 10 },
        { id: "id_7", name: "mack", sex: "man", age: 10 },
        { id: "id_8", name: "mack", sex: "man", age: 10 },
        { id: "id_9", name: "mack", sex: "man", age: 10 },
        { id: "id_3", name: "mack", sex: "man" },
        { id: "id_4", name: "mack", sex: "man", age: 10 },
        { id: "id_5", name: "mack", sex: "man", age: 10 },
        { id: "id_6", name: "mack", sex: "man", age: 10 },
        { id: "id_7", name: "mack", sex: "man", age: 10 },
        { id: "id_8", name: "mack", sex: "man", age: 10 },
        { id: "id_9", name: "mack", sex: "man", age: 10 },
        { id: "id_3", name: "mack", sex: "man" },
        { id: "id_4", name: "mack", sex: "man", age: 10 },
        { id: "id_5", name: "mack", sex: "man", age: 10 },
        { id: "id_6", name: "mack", sex: "man", age: 10 },
        { id: "id_7", name: "mack", sex: "man", age: 10 },
        { id: "id_8", name: "mack", sex: "man", age: 10 },
        { id: "id_9", name: "mack", sex: "man", age: 10 },
        { id: "id_3", name: "mack", sex: "man" },
        { id: "id_4", name: "mack", sex: "man", age: 10 },
        { id: "id_5", name: "mack", sex: "man", age: 10 },
        { id: "id_6", name: "mack", sex: "man", age: 10 },
        { id: "id_7", name: "mack", sex: "man", age: 10 },
        { id: "id_8", name: "mack", sex: "man", age: 10 },
        { id: "id_9", name: "mack", sex: "man", age: 10 },
        { id: "id_3", name: "mack", sex: "man" },
        { id: "id_4", name: "mack", sex: "man", age: 10 },
        { id: "id_5", name: "mack", sex: "man", age: 10 },
        { id: "id_6", name: "mack", sex: "man", age: 10 },
        { id: "id_7", name: "mack", sex: "man", age: 10 },
        { id: "id_8", name: "mack", sex: "man", age: 10 },
        { id: "id_9", name: "mack", sex: "man", age: 10 },
        { id: "id_3", name: "mack", sex: "man" },
        { id: "id_4", name: "mack", sex: "man", age: 10 },
        { id: "id_5", name: "mack", sex: "man", age: 10 },
        { id: "id_6", name: "mack", sex: "man", age: 10 },
        { id: "id_7", name: "mack", sex: "man", age: 10 },
        { id: "id_8", name: "mack", sex: "man", age: 10 },
        { id: "id_9", name: "mack", sex: "man", age: 10 },
        { id: "id_3", name: "mack", sex: "man" },
        { id: "id_4", name: "mack", sex: "man", age: 10 },
        { id: "id_5", name: "mack", sex: "man", age: 10 },
        { id: "id_6", name: "mack", sex: "man", age: 10 },
        { id: "id_7", name: "mack", sex: "man", age: 10 },
        { id: "id_8", name: "mack", sex: "man", age: 10 },
        { id: "id_9", name: "mack", sex: "man", age: 10 },
        { id: "id_3", name: "mack", sex: "man" },
        { id: "id_4", name: "mack", sex: "man", age: 10 },
        { id: "id_5", name: "mack", sex: "man", age: 10 },
        { id: "id_6", name: "mack", sex: "man", age: 10 },
        { id: "id_7", name: "mack", sex: "man", age: 10 },
        { id: "id_8", name: "mack", sex: "man", age: 10 },
        { id: "id_9", name: "mack", sex: "man", age: 10 },
        { id: "id_3", name: "mack", sex: "man" },
        { id: "id_4", name: "mack", sex: "man", age: 10 },
        { id: "id_5", name: "mack", sex: "man", age: 10 },
        { id: "id_6", name: "mack", sex: "man", age: 10 },
        { id: "id_7", name: "mack", sex: "man", age: 10 },
        { id: "id_8", name: "mack", sex: "man", age: 10 },
        { id: "id_9", name: "mack", sex: "man", age: 10 },
        { id: "id_3", name: "mack", sex: "man" },
        { id: "id_4", name: "mack", sex: "man", age: 10 },
        { id: "id_5", name: "mack", sex: "man", age: 10 },
        { id: "id_6", name: "mack", sex: "man", age: 10 },
        { id: "id_7", name: "mack", sex: "man", age: 10 },
        { id: "id_8", name: "mack", sex: "man", age: 10 },
        { id: "id_9", name: "mack", sex: "man", age: 10 },
        { id: "id_3", name: "mack", sex: "man" },
        { id: "id_4", name: "mack", sex: "man", age: 10 },
        { id: "id_5", name: "mack", sex: "man", age: 10 },
        { id: "id_6", name: "mack", sex: "man", age: 10 },
        { id: "id_7", name: "mack", sex: "man", age: 10 },
        { id: "id_8", name: "mack", sex: "man", age: 10 },
        { id: "id_9", name: "mack", sex: "man", age: 10 },
        { id: "id_3", name: "mack", sex: "man" },
        { id: "id_4", name: "mack", sex: "man", age: 10 },
        { id: "id_5", name: "mack", sex: "man", age: 10 },
        { id: "id_6", name: "mack", sex: "man", age: 10 },
        { id: "id_7", name: "mack", sex: "man", age: 10 },
        { id: "id_8", name: "mack", sex: "man", age: 10 },
        { id: "id_9", name: "mack", sex: "man", age: 10 },
        { id: "id_3", name: "mack", sex: "man" },
        { id: "id_4", name: "mack", sex: "man", age: 10 },
        { id: "id_5", name: "mack", sex: "man", age: 10 },
        { id: "id_6", name: "mack", sex: "man", age: 10 },
        { id: "id_7", name: "mack", sex: "man", age: 10 },
        { id: "id_8", name: "mack", sex: "man", age: 10 },
        { id: "id_9", name: "mack", sex: "man", age: 10 },
        { id: "id_3", name: "mack", sex: "man" },
        { id: "id_4", name: "mack", sex: "man", age: 10 },
        { id: "id_5", name: "mack", sex: "man", age: 10 },
        { id: "id_6", name: "mack", sex: "man", age: 10 },
        { id: "id_7", name: "mack", sex: "man", age: 10 },
        { id: "id_8", name: "mack", sex: "man", age: 10 },
        { id: "id_9", name: "mack", sex: "man", age: 10 },
        { id: "id_3", name: "mack", sex: "man" },
        { id: "id_4", name: "mack", sex: "man", age: 10 },
        { id: "id_5", name: "mack", sex: "man", age: 10 },
        { id: "id_6", name: "mack", sex: "man", age: 10 },
        { id: "id_7", name: "mack", sex: "man", age: 10 },
        { id: "id_8", name: "mack", sex: "man", age: 10 },
        { id: "id_9", name: "mack", sex: "man", age: 10 },
        { id: "id_3", name: "mack", sex: "man" },
        { id: "id_4", name: "mack", sex: "man", age: 10 },
        { id: "id_5", name: "mack", sex: "man", age: 10 },
        { id: "id_6", name: "mack", sex: "man", age: 10 },
        { id: "id_7", name: "mack", sex: "man", age: 10 },
        { id: "id_8", name: "mack", sex: "man", age: 10 },
        { id: "id_9", name: "mack", sex: "man", age: 10 },
        { id: "id_3", name: "mack", sex: "man" },
        { id: "id_4", name: "mack", sex: "man", age: 10 },
        { id: "id_5", name: "mack", sex: "man", age: 10 },
        { id: "id_6", name: "mack", sex: "man", age: 10 },
        { id: "id_7", name: "mack", sex: "man", age: 10 },
        { id: "id_8", name: "mack", sex: "man", age: 10 },
        { id: "id_9", name: "mack", sex: "man", age: 10 }
      ]
    };
  }
};
</script>
